services:
    - type: web
      name: payment gateway
      env: docker
      autoDeploy: true
      healthCheckPath: /healthz
      plan: free
      envVars:
          - key: DATABASE_URL
            fromDatabase:
                name: payment gateway db
                property: connectionString
          - key: NODE_ENV
            value: production
          - key: PORT
            value: 10000
          - key: JWT_SECRET
            generateValue: true
          - key: SQUARE_ACCESS_TOKEN
            value: xxxx-xxxx-xxxx-xxxx
databases:
    - name: payment gateway db
      plan: free
