services:
    - type: web
      name: payment gateway with square
      env: docker
      autoDeploy: true
      healthCheckPath: /healthz
      plan: free
      envVars:
          - key: DATABASE_URL
            fromDatabase:
                name: payment gateway with square db
                property: connectionString
          - key: NODE_ENV
            value: production
          - key: PORT
            value: 10000
          - key: JWT_SECRET
            generateValue: true
          - key: SQUARE_ACCESS_TOKEN
            value: --
    - type: web
      name: payment gateway frontend with square
      runtime: static
      buildCommand: true
      staticPublishPath: ./public
      headers:
          - path: /*
            name: Cache-Control
            value: no-cache
      autoDeploy: true
databases:
    - name: payment gateway with square db
      plan: free
